# Generated by Django 2.1 on 2018-08-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20180831_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='order',
            new_name='place',
        ),
    ]
